import { Router } from "express";
import healthRouter from "./health.js";
import companiesRouter from "./companies.js";
import employeesRouter from "./employees.js";
import departmentsRouter from "./departments.js";
import payrollRouter from "./payroll.js";
import timeTrackingRouter from "./timeTracking.js";
import leaveRouter from "./leave.js";
import benefitsRouter from "./benefits.js";
import analyticsRouter from "./analytics.js";
import onboardingRouter from "./onboarding.js";
import authRouter from "./auth.js";
import recruitmentRouter from "./recruitment.js";
import performanceRouter from "./performance.js";
import announcementsRouter from "./announcements.js";
import reportsRouter from "./reports.js";
import settingsRouter from "./settings.js";
import aiRouter from "./ai.js";
import expensesRouter from "./expenses.js";
import assetsRouter from "./assets.js";
import trainingRouter from "./training.js";
import insightsRouter from "./insights.js";

const router = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(companiesRouter);
router.use(employeesRouter);
router.use(departmentsRouter);
router.use(payrollRouter);
router.use(timeTrackingRouter);
router.use(leaveRouter);
router.use(benefitsRouter);
router.use(analyticsRouter);
router.use(onboardingRouter);
router.use(recruitmentRouter);
router.use(performanceRouter);
router.use(announcementsRouter);
router.use(reportsRouter);
router.use(settingsRouter);
router.use(aiRouter);
router.use(expensesRouter);
router.use(assetsRouter);
router.use(trainingRouter);
router.use(insightsRouter);

export default router;
