// Vercel serverless entry when the project root is artifacts/api-server.
// Import the bundled app so Vercel does not re-typecheck src/routes during function packaging.
// @ts-ignore - dist/app.mjs is generated by node ./build.mjs before Vercel packages functions.
import app from "../dist/app.mjs";

export default app;
