// Vercel serverless entry — @vercel/node compiles this TypeScript at deploy time.
// We import bundled app.mjs (NOT dist/index.mjs, which calls app.listen()).
// @ts-ignore - dist/app.mjs is generated by the build command before Vercel packages functions.
import app from "../artifacts/api-server/dist/app.mjs";
export default app;
